"""Levels 16–50: new base tool masters (Nano Banana 2, standard resolution, 9:16, paid)."""
T = "Create a production 2D game sprite for a casual {G} mobile game. Subject: {S} The entire {N} fits in the frame with {P}% clear padding on every side, nothing cropped. Style: semi-realistic glossy premium casual mobile game 3D render, soft studio key light from the upper left, {H}, no outlines. Background: plain uniform flat light gray background, no gradient, no cast shadow. {X}"

TOOLS = {
    'shared/tool-laser': ('cleaning and restoration', "one handheld industrial laser cleaning gun standing perfectly vertical: a short black emitter nozzle with a small red lens pointing straight up at the very top, a chunky dark gray and safety-orange gun body with cooling fins below it, a trigger and a rubber pistol grip at the bottom. Straight side view, centered, the nozzle on the vertical axis.", 'tool', 12, 'crisp specular highlights', 'No beam, no text, no logos, no hands, no extra objects.'),
    'shared/tool-spray-bottle': ('cleaning', "one plastic trigger spray bottle standing perfectly vertical with the nozzle pointing straight up at the very top: a white trigger sprayer head with the small nozzle opening at the top, a translucent turquoise bottle filled with blue cleaning liquid below. Straight side view, centered, the nozzle on the vertical axis.", 'bottle', 12, 'crisp highlights', 'No label, no text, no logos, no hands, no extra objects.'),
    'shared/tool-steam-cleaner': ('cleaning', "one handheld steam cleaner standing perfectly vertical: a narrow steam nozzle with a small round brush ring pointing straight up at the very top, a glossy white and sky-blue body with a clear water tank in the middle, and a handle with a trigger at the bottom. Straight side view, centered, the nozzle on the vertical axis.", 'tool', 12, 'crisp highlights', 'No steam, no text, no logos, no hands, no extra objects.'),
    'shared/tool-pump': ('cleaning', "one portable electric water pump with a suction hose: a round black strainer intake at the very top pointing up, a short black corrugated hose below it, and a compact glossy blue pump body with a carry handle at the bottom. Straight front view, centered.", 'tool', 12, 'crisp highlights', 'No water, no text, no logos, no hands, no extra objects.'),
    'shared/tool-hose': ('cleaning', "one garden hose spray nozzle standing perfectly vertical: a yellow and green plastic spray nozzle with the round water outlet pointing straight up at the very top, a pistol grip with a trigger, and a short coil of bright green garden hose at the bottom. Straight side view, centered, the outlet on the vertical axis.", 'tool', 12, 'crisp highlights', 'No water, no text, no logos, no hands, no extra objects.'),
    'shared/tool-skimmer-net': ('cleaning', "one pool skimmer net standing upright: a flat rectangular blue mesh net frame at the very top, and a long straight white aluminium telescopic pole going straight down. Straight front view, centered.", 'tool', 10, 'crisp highlights', 'No leaves, no text, no logos, no hands, no extra objects.'),
    'shared/tool-whetstone': ('restoration', "one knife sharpening whetstone held upright: a rectangular two-tone sharpening stone (gray coarse side and tan fine side) at the very top with its long flat edge facing up, mounted in a small dark wooden holder with a short handle going straight down. Straight front view, centered.", 'tool', 12, 'crisp highlights', 'No knife, no text, no logos, no hands, no extra objects.'),
    'shared/tool-carpet-beater': ('cleaning', "one traditional rattan carpet beater standing upright: a large woven rattan beating head shaped like a trefoil loop at the very top, and a straight wrapped rattan handle going straight down. Straight front view, centered.", 'tool', 10, 'crisp highlights', 'No text, no logos, no hands, no extra objects.'),
    'shared/tool-mop': ('cleaning', "one flat microfiber floor mop standing upside down so the mop head is at the very top: a wide flat rectangular light-blue microfiber pad facing up at the top, a swivel joint below it, and a long straight silver aluminium handle going straight down. Straight front view, centered.", 'mop', 10, 'crisp highlights', 'No water, no text, no logos, no hands, no extra objects.'),
}


def prompt(key):
    g, s, n, p, h, x = TOOLS[key]
    return T.format(G=g, S=s, N=n, P=p, H=h, X=x)

# Step 9 polish pass: three reusable tools for large surfaces / narrow gaps (same template)
TOOLS.update({
    'shared/tool-pool-brush': ('cleaning', "one telescopic pool and deck brush standing upright: a wide rectangular blue brush head with dense white bristles pointing straight up at the very top, mounted on a long straight white aluminium telescopic pole going straight down. Straight front view, centered, the brush head wide and horizontal.", 'brush', 10, 'crisp highlights', 'No water, no text, no logos, no hands, no extra objects.'),
    'shared/tool-wash-mitt': ('cleaning', "one large car wash mitt standing upright with the fluffy microfiber chenille noodle side at the very top: a thick plush light-blue chenille mitt with a dark blue elastic cuff at the bottom. Straight front view, centered.", 'mitt', 12, 'soft highlights', 'No hand inside, no text, no logos, no extra objects.'),
    'shared/tool-crevice-brush': ('cleaning', "one narrow crevice cleaning brush standing perfectly vertical: a thin pointed tip of stiff dark gray bristles at the very top, a slim angled neck, and a slender orange and gray plastic handle going straight down. Straight side view, centered, the bristle tip on the vertical axis.", 'brush', 12, 'crisp highlights', 'No text, no logos, no hands, no extra objects.'),
})
